fix cmake and xmake workflow

diff --git a/.github/workflows/test-xmake.yml b/.github/workflows/test-xmake.yml
--- a/.github/workflows/test-xmake.yml
+++ b/.github/workflows/test-xmake.yml
@@ -3,25 +3,31 @@ name: xmake
 on:
   push:
     branches: [main]
-    paths:
-      - ".github/workflows/xmake.yml"
-      - "include/**"
-      - "src/**"
-      - "tests/**"
-      - "xmake.lua"
 
   pull_request:
     branches: [main]
-    paths:
-      - ".github/workflows/xmake.yml"
-      - "include/**"
-      - "src/**"
-      - "tests/**"
-      - "config/**"
-      - "xmake.lua"
 
 jobs:
+  check-changes:
+    runs-on: ubuntu-latest
+    outputs:
+      cpp: ${{ steps.filter.outputs.cpp }}
+    steps:
+      - uses: dorny/paths-filter@v3
+        id: filter
+        with:
+          filters: |
+            cpp:
+              - ".github/workflows/xmake.yml"
+              - "include/**"
+              - "src/**"
+              - "tests/**"
+              - "config/**"
+              - "xmake.lua"
+
   build:
+    needs: check-changes
+    if: ${{ needs.check-changes.outputs.cpp == 'true' }}
     strategy:
       fail-fast: false
       matrix:
@@ -58,14 +64,29 @@ jobs:
           locked: true
 
       - name: Build
-        run: |
-          pixi run ci-xmake-build ${{ matrix.build_type }}
+        run: pixi run ci-xmake-build ${{ matrix.build_type }}
 
       - name: Test
-        run: |
-          pixi run xmake-test
+        run: pixi run xmake-test
 
-      # Clean up llvm package to reduce cache size
       - name: Remove llvm package (Linux)
         if: runner.os == 'Linux'
         run: xmake require --uninstall clice-llvm
+
+  check-passed:
+    if: always()
+    needs: [build]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Decide status
+        run: |
+          if [ "${{ contains(needs.*.result, 'failure') }}" = "true" ]; then
+            echo "❌ Build failed."
+            exit 1
+          fi
+          if [ "${{ contains(needs.*.result, 'cancelled') }}" = "true" ]; then
+            echo "🛑 Build cancelled."
+            exit 1
+          fi
+          echo "✅ All builds passed or skipped."
+          exit 0
